version: "3.9"

services:
  color-camera:
    build: .
    restart: unless-stopped
    network_mode: host
    privileged: true
    group_add:
      - video
    env_file:
      - camera.env
    environment:
      # Allow overrides without editing camera.env
      SERVICE_HOST: ${SERVICE_HOST:-0.0.0.0}
      SERVICE_PORT: ${SERVICE_PORT:-8104}
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - type: tmpfs
        target: /tmp
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:8104/camera/status"]
      interval: 30s
      timeout: 5s
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
